-- Supabase SQL: 创建 todos 数据表
-- 用于 my-todo-app 项目

-- 创建表
CREATE TABLE todos (
  id bigint generated by default as identity primary key,
  title text not null,
  completed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 允许所有人读写（开发阶段用）
ALTER TABLE todos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON todos FOR ALL USING (true) WITH CHECK (true);
